name: Update National Data Manually

on:
  workflow_dispatch:
  schedule:
    # Runs at 06:00 UTC every day
    - cron: '0 6 * * *'

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build valid counties list
        run: python build_valid_counties.py

      - name: Run data build script
        run: python build_national_view.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add national_latest.parquet valid_counties.csv
          # Commit only if there are changes, otherwise the workflow will fail
          git diff --staged --quiet || git commit -m "Automated national data update"
          # Pull the latest changes from the remote to avoid non-fast-forward errors
          git pull --rebase
          git push
