[theme]
# A professional and clean color scheme
primaryColor="#0068c9"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f5f5"
textColor="#262730"
font="sans serif"

[server]
fileWatcherType = "none"
